### PR TITLE
Check for NULL window in WinNativeEventFilter::nativeEventFilter()

### LINKED ISSUE #37: [Windows] [Win10] Assert error after enabling Acrylic effect
image

### PR DESCRIPTION
**Pull request by JulienMaille**
Will fix #37

### CODE REVIEW

**Comment by wangwenx190** [comment]
Thanks! It really works!

**Comment by wangwenx190** [comment]
I don't merge your PRs because I don't know how to edit them. They need some modification before merging...
Hope you don't feel uncomfortable about this.

**Comment by JulienMaille** [comment]
I feel highly disrespected! :-þ

**Comment by wangwenx190** [comment]
> 
> 
> I feel highly disrespected! :-þ

I'm really sorry, bro.

**Comment by wangwenx190** [comment]
Could you teach me how to edit PRs before merging? I'm not good at using GitHub.

**Comment by JulienMaille** [comment]
I was joking! I'm not sure you can edit PR, you can ask the contributer to fix things by adding more commits but I don't know if you can edit by yourself.

**Comment by wangwenx190** [comment]
> 
> I was joking!
>

Looks like I'm lucky enough. I also don't like people who disrespect others.

>
> you can ask the contributer to fix things by adding more commits
>

Yes I know this, let me find how to edit the PR directly on GitHub.

**Pull request closed without merging**
