### PR TITLE
FIX #92 do not call startSystemMove2 in MousePressEvent

### LINKED ISSUE #92: Issues with mouse tracking when dismissing a popup by clicking on the top bar
I noticed a weird behavior of the mouse after a certain sequence happens.
You will see in the movie that buttons hovering is broken, but there's more issues when opening menus for instance.

Here is how to reproduce it.
- Unfold a widget like a combo box, a toolmenu or a QMenu
- Click in the title bar (but not in a section that has been processed by `FramelessWindowsManager::setHitTestVisible()`
- Now the mouse tracking is broken

It can be fixed by reopening the widget and clicking somewhere else, or my dragging the window or even by clicking outside the window.
frameless2

It seems something is happening in `FramelessHelperWin::nativeEventFilter()`

### PR DESCRIPTION
**Pull request by JulienMaille**

### CODE REVIEW

**Comment by JulienMaille** [comment]
@wangwenx190 updated to your latest refactoring

**Comment by wangwenx190** [comment]
> @wangwenx190 updated to your latest refactoring

Thanks a lot! Let me test this pr.

**Comment by wangwenx190** [comment]
#92 is fixed indeed! Thanks very much! but since you are touching this issue, can you fix the Quick module as well?

**Comment by JulienMaille** [comment]
I don't compile QtQuick here so I had to blindly commit the same fix

**Comment by wangwenx190** [comment]
> I don't compile QtQuick here so I had to blindly commit the same fix

Doesn't matter, I've tried your fix in the quick module already, it compiles and works.

**Comment by wangwenx190** [comment]
Will you modify this pr again later? If not, I'm going to merge this pr into the wip branch.

**Comment by JulienMaille** [comment]
No I think PR is complete

**Pull request merged**
