### PR TITLE
identify a screen by its name when serial number is empty

### PR DESCRIPTION
**Pull request by JulienMaille**

### CODE REVIEW

**Comment by wangwenx190** [comment]
Thanks! But are you sure the name property is different for every monitor? Can we use it to identify different monitors?

**Comment by JulienMaille** [comment]
> Thanks! But are you sure the name property is different for every monitor? Can we use it to identify different monitors?

At least it works on my system

**Comment by wangwenx190** [comment]
>
> At least it works on my system
>
OK. Thanks for your contribution.

**Comment by wangwenx190** [comment]
Done in the latest commit: b736936a8ada824d0a34ad2f66feb76935eb070c

**Comment by wangwenx190** [comment]
This solution is not perfect enough. I tested it through a Qt Quick application and found that the window might get stuck while moving rapidly.

**Comment by wangwenx190** [comment]
But it's already much better than calling `updateWindow()` all the time while moving.

**Comment by wangwenx190** [comment]
I think maybe the overhead of querying the current screen's serial number and name and compare the two QStrings is bigger than we expected.

**Pull request closed without merging**
