### PR TITLE
Fix "out of boundaries" line drawing

### PR DESCRIPTION
**Pull request by JulienMaille**
drawLine on [0, w-1]

### CODE REVIEW

**Comment by wangwenx190** [comment]
What does this pr fix or improve? Why a -1 is needed?

**Comment by JulienMaille** [comment]
Aren't you drawing to far with original code?

**Comment by wangwenx190** [comment]
> Aren't you drawing too far with original code?

It might be, but will this pr make any visual difference?

**Comment by wangwenx190** [comment]
Or is this pr not complete yet, you will fill in more fixups or improvements later?

**Comment by JulienMaille** [comment]
No, it was just a small fix as this looked like an "out of boundaries" drawing mistake. Feel free to dismiss it

**Comment by wangwenx190** [comment]
> No, it was just a small fix as this looked like an "out of boundaries" drawing mistake. Feel free to dismiss it

I will not dismiss it if it really fix something, no matter how small the issue is. But the pr's title is too general, can you update it to be a little more specific?

**Pull request merged**
